website/controllers/classification.py
from math import nan
from sklearn.calibration import LabelEncoder
from sklearn.metrics import confusion_matrix
from website.models import Models
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from flask import flash, json, request
import pickle
import os
import numpy as np

from website.multinb import MultiNB

class ClassificationController:
    def createModel(self, num = ""):

        # instance_model = Models('SELECT COUNT(id) as jumlah FROM tbl_data_train WHERE clean_text IS NOT NULL AND sentiment IS NOT NULL')
        # sentiment_count = instance_model.select()

        # instance_model = Models("SELECT COUNT(id) as positif FROM tbl_data_train WHERE clean_text IS NOT NULL AND sentiment = 'positif'")
        # sentiment_positif = instance_model.select()

        # instance_model = Models("SELECT COUNT(id) as negatif FROM tbl_data_train WHERE clean_text IS NOT NULL AND sentiment = 'negatif'")
        # sentiment_negatif = instance_model.select()

        mdl = request.form["model"]
        print(mdl)

        # Data Training
        list_text_training = []
        list_label_training = []

        instance_model = Models(f'SELECT clean_text, sentiment, user FROM tbl_data_train_q{num}')
        data_train = instance_model.select()

        for i in range(len(data_train)):
            list_text_training.append(data_train[i]['clean_text'])
            list_label_training.append(data_train[i]['sentiment'])

        # Data Testing
        list_text_testing = []
        list_label_testing = []

        instance_model = Models(f'SELECT clean_text, sentiment, user FROM tbl_data_test_q{num}')
        data_test = instance_model.select()
        for i in range(len(data_test)):
            list_text_testing.append(data_test[i]['clean_text'])
            list_label_testing.append(data_test[i]['sentiment'])

        # Vectorize X_train X_test
        vectorizer = CountVectorizer()
        X_train = vectorizer.fit_transform(list_text_training).toarray()
        X_test = vectorizer.transform(list_text_testing).toarray()
        vocab = vectorizer.get_feature_names_out()

        # Vectorize y_train y_test
        labelEncoder = LabelEncoder()
        y_train = labelEncoder.fit_transform(list_label_training).ravel()
        y_test = labelEncoder.transform(list_label_testing).ravel()

        label = labelEncoder.classes_

        # TRAIN MULTINOMIAL NAIVE BAYES
        if mdl == "mnb" :
            model = MultiNB()
        else :
            model = GaussianNB()

        model.fit(X_train, y_train)

        # SAVE MODEL as PKL
        filename = f'mnb_model{num}.pkl'
        path = 'website/static/model_data/'
        with open(os.path.join(path, filename), 'wb') as out_name:
            pickle.dump(model, out_name, pickle.HIGHEST_PROTOCOL)

        # EVALUATION
        y_pred = model.predict(X_test)

        # Mengambil hasil prediksi label
        list_label_prediksi = []

        for i in range(len(y_pred)):
            if y_pred[i] == 0:
                list_label_prediksi.append("Tidak Puas")
            elif y_pred[i] == 1:
                list_label_prediksi.append("Cukup")
            elif y_pred[i] == 2:
                list_label_prediksi.append("Puas")

        # Mengambil hasil probabilitas prediksi label
        list_prob_prediksi = []

        if mdl == "mnb":
            predict_prob = model.predict_proba
        else:
            predict_prob = model.predict_proba(X_train)

        for i in range(len(predict_prob)):
            tuple_pred = (round(float(predict_prob[i][0]), 3), round(float(predict_prob[i][1]), 3), round(float(predict_prob[i][2]), 3))
            list_prob_prediksi.append(tuple_pred)

        conf = confusion_matrix(y_test, y_pred)
        print(conf)
        TTidakPuas, FTidakPuas1, FTidakPuas2, FCukup1, TCukup, FCukup2, FPuas1, FPuas2, TPuas = confusion_matrix(y_test, y_pred).ravel()

        akurasi = (TTidakPuas + TCukup + TPuas) / (TTidakPuas + FTidakPuas1 + FTidakPuas2 + TCukup + FCukup1 + FCukup2 + FPuas1 + FPuas2 + TPuas)

        if ((TTidakPuas + FCukup1 + FPuas1) != 0):
            presisi_negatif = TTidakPuas / (TTidakPuas + FCukup1 + FPuas1)
        else: 
            presisi_negatif = 0
        
        if ((TCukup + FTidakPuas1 + FPuas2)):
            presisi_netral = TCukup / (TCukup + FTidakPuas1 + FPuas2)
        else:
            presisi_netral = 0 

        if ((TPuas + FTidakPuas2 + FCukup2) != 0):
            presisi_positif = TPuas / (TPuas + FTidakPuas2 + FCukup2)
        else:
            presisi_positif = 0

        presisi = (presisi_negatif + presisi_netral + presisi_positif) / len(label)

        if ((TTidakPuas + FTidakPuas1 + FTidakPuas1) != 0):
            recall_negatif = TTidakPuas / (TTidakPuas + FTidakPuas1 + FTidakPuas1)
        else:
            recall_negatif = 0

        if ((TCukup + FCukup1 + FCukup2)):
            recall_netral = TCukup / (TCukup + FCukup1 + FCukup2)
        else:
            recall_netral = 0

        if ((TPuas + FPuas1 + FPuas2)):
            recall_positif = TPuas / (TPuas + FPuas1 + FPuas2) 
        else:
            recall_positif = 0

        recall = (recall_negatif + recall_netral + recall_positif) / len(label)

        data_dict = {
            "text_list" : list_text_testing,
            "label_list" : list_label_testing,
            "predict_label" : list_label_prediksi,
            "predict_prob" : list_prob_prediksi,
            "tneg" : int(TTidakPuas),
            "fneg1" : int(FTidakPuas1),
            "fneg2" : int(FTidakPuas2),
            "fnet1" : int(FCukup1),
            "tnet" : int(TCukup),
            "fnet2" : int(FCukup2),
            "fpos1" : int(FPuas1),
            "fpos2" : int(FPuas2),
            "tpos" : int(TPuas),
            "jumlah_kelas": int(len(label)),
            "presisi_negatif" : round(float(presisi_negatif), 2),
            "presisi_netral" : round(float(presisi_netral), 2),
            "presisi_positif" : round(float(presisi_positif), 2),
            "recall_negatif" : round(float(recall_negatif), 2),
            "recall_netral" : round(float(recall_netral), 2),
            "recall_positif" : round(float(recall_positif), 2),
            "akurasi" : round(float(akurasi), 2),
            "presisi" : round(float(presisi), 2),
            "recall" : round(float(recall), 2)
        }

        # Menyimpan hasil evaluasi dalam bentuk json
        with open(os.path.join(path, f'hasil_evaluasi_model{num}.json'), 'w') as outfile:
            json.dump(data_dict, outfile, indent=2)

        flash('Berhasil melakukan klasifikasi data.', 'success')

        return 'true'

    def getEvaluation(self):
        path = 'website/static/model_data/'
        data = {}
        for num in range(1, 6):
            filename = f'hasil_evaluasi_model{num}.json'

            try:
                data[f"eval_{num}"] = json.load(open(path+filename))
            except:
                data = {}

        return data


    def deleteEvalutaion(self):
        filepath = 'website/static/model_data/hasil_evaluasi_model.json'

        if os.path.exists(filepath):
            os.remove(filepath)
            flash('Berhasil menghapus data.', 'success')

        return None

website/views.py
import json
from urllib import response
from flask import Blueprint, jsonify, render_template, request, flash, redirect, url_for
from website.controllers.crawling import CrawlingController

from website.controllers.dashboard import DashboardController
from website.controllers.kamus import KamusController
from website.controllers.labeling import LabelingController
from website.controllers.classification import ClassificationController
from website.controllers.preprocessing import PreprocessingController
from website.controllers.splitting import SplittingController
from website.controllers.visualization import VisualizationController

views = Blueprint('views', __name__)

# DASHBOARD

controller_dashboard = DashboardController()
@views.route('/', methods=['GET'])
def dashboard():
    data = controller_dashboard.getData()
    return render_template("dashboard.html", data=data)

# KAMUS
controller_kamus = KamusController()
@views.route('/kamus', methods=['GET'])
def kamus():
    return render_template("kamus.html")

## Slangword
@views.route('/kamus/list-slangword', methods=['GET'])
def list_slangword():
    slangword = controller_kamus.select_dataSlangword()
    return { 'data' : slangword }

@views.route('/kamus/slangword/tambah', methods=['POST'])
def tambah_slangword():
    controller_kamus.add_dataSlangword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/slangword/import', methods=['POST'])
def import_data_slangword():
    controller_kamus.import_dataSlangword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/slangword/ubah', methods=['POST'])
def ubah_slangword():
    controller_kamus.update_dataSlangword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/slangword/hapus', methods=['POST'])
def hapus_slangword():
    controller_kamus.delete_dataSlangword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/slangword/hapus-all', methods=['POST'])
def hapus_all_slangword():
    controller_kamus.delete_allDataSlangword()
    return redirect(url_for('views.kamus'))

# Stopword
@views.route('/kamus/list-stopword', methods=['GET'])
def list_stopword():
    stopword = controller_kamus.select_dataStopword()
    return { 'data' : stopword }

@views.route('/kamus/stopword/tambah', methods=['POST'])
def tambah_stopword():
    controller_kamus.add_dataStopword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/stopword/import', methods=['POST'])
def import_data_stopword():
    controller_kamus.import_dataStopword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/stopword/ubah', methods=['POST'])
def ubah_stopword():
    controller_kamus.update_dataStopword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/stopword/hapus', methods=['POST'])
def hapus_stopword():
    controller_kamus.delete_dataStopword()
    return redirect(url_for('views.kamus'))

@views.route('/kamus/stopword/hapus-all', methods=['POST'])
def hapus_all_stopword():
    controller_kamus.delete_allDataStopword()
    return redirect(url_for('views.kamus'))


# CRAWLING
controller_crawling = CrawlingController()

@views.route('/crawling', methods=['GET'])
def crawling():
    data_crawling = controller_crawling.select_data_crawling()
    return render_template("crawling.html", data=data_crawling)

@views.route('/import-crawling', methods=['POST'])
def import_crawling():
    controller_crawling.import_crawlingExcel()
    return redirect(url_for('views.crawling'))


# PREPROCESSING
controller_preprocessing = PreprocessingController()

@views.route('/preprocessing', methods=['GET','POST'])
def preprocessing():
    if request.method == 'GET':
        count_data_crawling = controller_preprocessing.count_dataCrawling()
        return render_template("preprocessing.html", count_data_crawling=count_data_crawling)

    if request.method == 'POST':
        response = controller_preprocessing.add_dataPreprocessing()
        return response

@views.route('/list-data-preprocessing', methods=['GET'])
def list_data_preprocessing():
    data_preprocessing = controller_preprocessing.select_dataPreprocessing()
    return { 'data' : data_preprocessing }

# LABELING
controller_labeling = LabelingController()

@views.route('/labeling', methods=['GET','POST'])
def labeling():
    if request.method == 'GET':
        count_data_with_label = controller_labeling.count_dataWithLabel()
        return render_template("labeling.html", count_data_with_label=count_data_with_label)
    
    if request.method == 'POST':
        response = controller_labeling.add_dataLabeling()
        return response

@views.route('/list-data-with-label', methods=['GET'])
def list_data_with_label():
    data_with_label = controller_labeling.select_dataWithLabel()
    return { 'data' : data_with_label }

@views.route('/list-data-no-label', methods=['GET'])
def list_data_no_label():
    data_no_label = controller_labeling.select_dataNoLabel()
    return { 'data' : data_no_label }

@views.route('/labeling/hapus-all', methods=['POST'])
def hapus_all_label():
    controller_labeling.delete_dataLabeling()
    return redirect(url_for('views.labeling'))


# SPLITTING DATA
controller_splitting = SplittingController()

@views.route('/split', methods=['GET', 'POST'])
def split():
    if request.method == 'GET':
        count_data_with_label = controller_splitting.count_dataWithLabel()
        count_data_with_label_pos = controller_splitting.count_dataWithLabelPos()
        count_data_with_label_neg = controller_splitting.count_dataWithLabelNeg()

        count_data_q1_label = controller_splitting.count_dataQ1WithLabel()
        count_data_q2_label = controller_splitting.count_dataQ2WithLabel()
        count_data_q3_label = controller_splitting.count_dataQ3WithLabel()
        count_data_q4_label = controller_splitting.count_dataQ4WithLabel()
        count_data_q5_label = controller_splitting.count_dataQ5WithLabel()

        if count_data_with_label_pos != 0:
            percentage_pos = round((count_data_with_label_pos / count_data_with_label) * 100)
        else:
            percentage_pos = 0

        if count_data_with_label_neg != 0:
            percentage_neg = round((count_data_with_label_neg / count_data_with_label) * 100)
        else:
            percentage_neg = 0

        return render_template("splitting.html", count_data_with_label=count_data_with_label, 
        count_data_with_label_pos=count_data_with_label_pos, 
        count_data_with_label_neg=count_data_with_label_neg,
        count_data_q1_label=count_data_q1_label,
        count_data_q2_label=count_data_q2_label,
        count_data_q3_label=count_data_q3_label,
        count_data_q4_label=count_data_q4_label,
        count_data_q5_label=count_data_q5_label,
        percentage_pos=percentage_pos,
        percentage_neg=percentage_neg)
    
    if request.method == 'POST':
        response = controller_splitting.add_dataSplit()
        return response

@views.route('/split/list-data-train-q1', methods=['GET'])
def list_data_train_q1():
    data_train = controller_splitting.select_dataTrainQ1()
    return { 'data' : data_train }

@views.route('/split/list-data-test-q1', methods=['GET'])
def list_data_test_q1():
    data_test = controller_splitting.select_dataTestQ1()
    return { 'data' : data_test }

@views.route('/split/list-data-train-q2', methods=['GET'])
def list_data_train_q2():
    data_train = controller_splitting.select_dataTrainQ2()
    return { 'data' : data_train }

@views.route('/split/list-data-test-q2', methods=['GET'])
def list_data_test_q2():
    data_test = controller_splitting.select_dataTestQ2()
    return { 'data' : data_test }

@views.route('/split/list-data-train-q3', methods=['GET'])
def list_data_train_q3():
    data_train = controller_splitting.select_dataTrainQ3()
    return { 'data' : data_train }

@views.route('/split/list-data-test-q3', methods=['GET'])
def list_data_test_q3():
    data_test = controller_splitting.select_dataTestQ3()
    return { 'data' : data_test }

@views.route('/split/list-data-train-q4', methods=['GET'])
def list_data_train_q4():
    data_train = controller_splitting.select_dataTrainQ4()
    return { 'data' : data_train }

@views.route('/split/list-data-test-q4', methods=['GET'])
def list_data_test_q4():
    data_test = controller_splitting.select_dataTestQ4()
    return { 'data' : data_test }

@views.route('/split/list-data-train-q5', methods=['GET'])
def list_data_train_q5():
    data_train = controller_splitting.select_dataTrainQ5()
    return { 'data' : data_train }

@views.route('/split/list-data-test-q5', methods=['GET'])
def list_data_test_q5():
    data_test = controller_splitting.select_dataTestQ5()
    return { 'data' : data_test }

@views.route('/split/hapus', methods=['POST'])
def hapus_dataSplit():
    controller_splitting.delete_allDataSplit()
    return redirect(url_for('views.split'))

# CLASSIFICATION
controller_classification = ClassificationController()
@views.route('/classification', methods=['GET','POST'])
def classification():
    if request.method == 'GET':
        data_eval = controller_classification.getEvaluation()
        return render_template("classification.html", data_eval=data_eval)

    if request.method == 'POST':
        for num in range(1, 6):
            controller_classification.createModel(num)
        return controller_classification.createModel(1)

@views.route('/classification/hapus-data', methods=['POST'])
def hapus_evaluation():
    controller_classification.deleteEvalutaion()
    return redirect(url_for('views.classification'))

# VISUALISASI
controller_visualisasi = VisualizationController()
@views.route('/visualization', methods=['GET', 'POST'])
def visualization():
    if request.method == 'GET':
        data = controller_visualisasi.getVisualisasi()
        return render_template('visualization.html', data=data)
    
    if request.method == 'POST':
        response = controller_visualisasi.createVisualisasi()

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
      type="text/css"
    />
    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
      type="text/css"
    />
    <!-- DataTables -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/dataTables.bootstrap5.min.css') }}"
      type="text/css"
    />
    <!-- Boxicons CDN Link -->
    <link
      href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
      rel="stylesheet"
    />

    <title>{% block title %}Dashboard{% endblock title %}</title>
  </head>
  <body>
    <div class="sidebar">
      <div class="logo-content">
        <div class="logo">
          <i class="bx bxl-flask"></i>
          <div class="logo-name">TEXT MINING</div>
        </div>
        <a id="btn-menu"><i class="bx bx-menu-alt-left"></i></a>
      </div>
      <ul class="nav-list">
        <li>
          <a href="{{ url_for('views.dashboard') }}">
            <i class="bx bxs-dashboard"></i>
            <span class="link-name">Dashboard</span>
          </a>
          <span class="tool-tip">Dashboard</span>
        </li>
        <li>
          <a href="{{ url_for('views.kamus') }}">
            <i class='bx bx-book-add' ></i>
            <span class="link-name">Kamus Data</span>
          </a>
          <span class="tool-tip">Kamus Data</span>
        </li>
        <li>
          <a href="{{ url_for('views.crawling') }}">
            <i class="bx bxs-file-doc"></i>
            <span class="link-name">Data Kuesioner</span>
          </a>
          <span class="tool-tip">Data Kuesioner</span>
        </li>
        <li>
          <a href="{{ url_for('views.preprocessing') }}">
            <i class="bx bx-analyse"></i>
            <span class="link-name">Preprocessing</span>
          </a>
          <span class="tool-tip">Preprocessing</span>
        </li>
        <li>
          <a href="{{ url_for('views.split') }}">
            <i class="bx bx-columns"></i>
            <span class="link-name">Splitting Data</span>
          </a>
          <span class="tool-tip">Splitting Data</span>
        </li>
        <li>
          <a href="{{ url_for('views.classification') }}">
            <i class='bx bx-cog'></i>
            <span class="link-name">Classification</span>
          </a>
          <span class="tool-tip">Classification</span>
        </li>
        <li>
          <a href="{{ url_for('views.visualization') }}">
            <i class='bx bx-bar-chart-alt-2'></i>
            <span class="link-name">Visualization</span>
          </a>
          <span class="tool-tip">Visualization</span>
        </li>
      </ul>
    </div>

    <main class="main">
      <div class="base-container">
        <div class="row">{% block content %} {% endblock content %}</div>
      </div>
    </main>

    <!-- Scripts -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/bootstrap.min.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery-3.5.1.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/dataTables.bootstrap5.min.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/moment-with-locales.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/chart.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/scripts.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/ajax.js') }}"
    ></script>
  </body>
</html>

website/templates/dashboard.html
{% extends 'base.html' %} {% block title %}Dashboard{% endblock title %} {%
block content %}

<div class="container w-75 text-center">
  <h3>Klasifikasi Tingkat Kepuasan Pelanggan Sat & Sun : The Almeaty Service Menggunakan Metode <em>Naive Bayes</em></h3>
  <h4>19082010069 - Mariska Regina RahmaPutri</h4>
</div>
<hr />
<div class="col-12 col-lg-9 mb-4">
  <div class="row">
    <div class="col-6 col-lg-4 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <div class="stats-icon blue">
                <i class='bx bxs-file-doc'></i>
              </div>
            </div>
            <div class="col-md-8">
              <h5>Data Kuesioner</h5>
              <h4 class="text-dark" id="countDataCrawling">
                {{ data.data_crawling }}
              </h4>
            </div>
            <div class="d-flex justify-content-center">
              <a
                href="{{ url_for('views.crawling') }}"
                class="btn btn-outline-primary btn-sm"
                >Lihat Detail</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-6 col-lg-4 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <div class="stats-icon green">
                <i class="bx bx-analyse"></i>
              </div>
            </div>
            <div class="col-md-8">
              <h5>Data <em>Preprocessing</em></h5>
              <h4 class="text-dark" id="countDataPreprocess">
                {{ data.data_preprocess }}
              </h4>
            </div>
            <div class="d-flex justify-content-center">
              <a
                href="{{ url_for('views.preprocessing') }}"
                class="btn btn-outline-primary btn-sm"
                >Lihat Detail</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-6 col-lg-4 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <div class="stats-icon red">
                <i class="bx bx-purchase-tag"></i>
              </div>
            </div>
            <div class="col-md-8">
              <h5>Data ber<em>label</em></h5>
              <h4 class="text-dark" id="countDataLabel">
                {{ data.data_berlabel }}
              </h4>
            </div>
          </div>
          <div class="d-flex justify-content-center">
            <a
              href="{{ url_for('views.labeling') }}"
              class="btn btn-outline-primary btn-sm"
              >Lihat Detail</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-body">
          <p id="countDataTrain" hidden>{{ data.data_train }}</p>
          <p id="countDataTest" hidden>{{ data.data_test }}</p>
          <p id="countDataSlangword" hidden>{{ data.data_slangword }}</p>
          <p id="countDataStopword" hidden>{{ data.data_stopword }}</p>
          <h4 class="card-title text-center">Chart Data</h4>
          <canvas id="myChart" height="100"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-12 col-lg-3">
  <div class="row">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-center">Chart Pembagian Data</h4>
        <canvas id="chart-split-data"></canvas>
        {% if (data.data_train and data.data_test) %}
        <p class="text-center">Uji : Latih <br />
          {{ "%.2f"|format(data.data_train / (data.data_train + data.data_test) * 100) }} % : {{
          "%.2f"|format(data.data_test / (data.data_train + data.data_test) * 100) }} %
        </p>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card mt-4">
      <div class="card-body">
        <div class="vstack gap-2 mx-auto">
          <a
            href="{{ url_for('views.split') }}"
            class="btn btn-outline-primary btn-sm"
            >Buat Pembagian Data</a
          >
          <a
            href="{{ url_for('views.classification') }}"
            class="btn btn-outline-primary btn-sm"
            >Buat Klasifikasi Data</a
          >
          <a href="#" class="btn btn-outline-primary btn-sm"
            >Buat Visualisasi Data</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}